language: python
cache: pip
python:
- '3.5'
# - '3.6-dev'
# - 'nightly'
install:
- make install
script:
- make lint
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: samuelcolvin
  password:
    secure: BU1y35XOmuebWgz/fAXutjoJ2sxdVSI50nsTgwl/3T2AvEtDh+IWwDqzB5/wLGexZen1HGAofyq8r+endqT+xtL49gIxtXhkw1sNuXE3HY1ELolwBy5Ht/95Sw9uOZge5Hl3eGMyMpUR9x9U86tn5Fg0+Pg0FpfQ+/150z/UBCGLPt+WZa99MoQknjj2KjsJKY30aqgqxW2YJLrUER2AtzkRfcnPjZWzhon5XZWTPCvS2F6takoYS0lDuz7TcpMZjQxxGC3vQhLqinpZS0Fvj4Ct7WDc4XbcAFDFgwdVskQF9hqKNXDexvnCmUMriUWE5vXRIYGAsEFlvcQ6/uBNxzGBbeSs1l2GaORudi3vNGCMscDd6tXXVttwOhSxXHxFUBejee8WnlnUooly/3LG+8ExjaE5A6/K/3iRSUAoQ9NCr8AGwIkwR1JEWCKr3fBuLwE4mWPL4gQRhjFQn6baF6SCndDPm6XRy6mugX6NmIYMwBgXXdv5P0QivNJ26NdM24SI5zA29XRHCXRLhDN4Xn7dL3Oj7Tvs6y8Xrb6UfVB2uX1aE8iKtmqDHCur5QbuFCFxnOOToZ3tvwlilrFx8ngBIMWFVP52c11Vr4MFI4HXwdizhSUNC1mSU3zeU9Lvt16rK4Kmt+rE0x3VOvZwg1PNI99tS7WpQZp3ZdgMRDU=
  distributions: sdist bdist_wheel
  on:
    tags: true
